---
weapons:
  - id: bow
    rangeMin: 1
    rangeMax: 3
    canMoveAndAttack: true
    baseDamage:
      land: 1
      water: 1
      air: 1
    tagDamage:
      archer: 0.65
      ballista: 0.3
      balloon: 0.2
      dog: 0.75
      dragon: 0.1
      giant: 0.15
      harpoonship: 0.2
      harpy: 0.3
      knight: 0.4
      mage: 0.75
      merman: 0.7
      rifleman: 0.8
      soldier: 0.7
      spearman: 0.6
      structure: 0.2
      thief: 0.7
      travelboat: 0.2
      trebuchet: 0.25
      turtle: 0.2
      villager: 0.7
      wagon: 0.35
      warship: 0.2
      witch: 0.2
      commander_caesar: 0.1
      commander_darkmercia: 0.05
      commander_elodie: 0.1
      commander_emeric: 0.1
      commander_greenfinger: 0.05
      commander_koji: 0.05
      commander_mercia: 0.05
      commander_mercival: 0.05
      commander_nuru: 0.1
      commander_ragna: 0.05
      commander_ryota: 0.1
      commander_sedge: 0.1
      commander_sigrid: 0.1
      commander_tenri: 0.1
      commander_twins: 0.1
      commander_valder: 0.1
      commander_vesper: 0.1
      commander_wulfar: 0.05

modifyingUnitClasses:
  - id: archer
    replace:
      cost: 400
---
