---
weapons:
  - id: ballistaBolt
    rangeMin: 2
    rangeMax: 6
    canMoveAndAttack: false
    baseDamage:
      land: 1
      water: 1
      air: 1
    tagDamage:
      archer: 0.3
      ballista: 0.2
      balloon: 1.1
      dog: 0.5
      dragon: 0.85
      giant: 0.2
      harpoonship: 0.2
      harpy: 1.3
      knight: 0.25
      mage: 0.4
      merman: 0.4
      rifleman: 0.5
      soldier: 0.4
      spearman: 0.3
      structure: 0.3
      thief: 0.4
      travelboat: 0.2
      trebuchet: 0.1
      turtle: 0.2
      villager: 0.4
      wagon: 0.3
      warship: 0.2
      witch: 0.95
      commander_caesar: 0.2
      commander_darkmercia: 0.05
      commander_elodie: 0.15
      commander_emeric: 0.15
      commander_greenfinger: 0.1
      commander_koji: 0.1
      commander_mercia: 0.1
      commander_mercival: 0.1
      commander_nuru: 0.15
      commander_ragna: 0.05
      commander_ryota: 0.15
      commander_sedge: 0.15
      commander_sigrid: 0.15
      commander_tenri: 0.15
      commander_twins: 0.15
      commander_valder: 0.15
      commander_vesper: 0.1
      commander_wulfar: 0.1


modifyingUnitClasses:
  - id: ballista
    replace:
      cost: 750
---
