---
weapons:
  - id: kojiAttack
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
    tagDamage:
      archer: 1.35
      ballista: 0.65
      dog: 1.2
      giant: 0.45
      knight: 0.6
      mage: 0.85
      merman: 1.00
      rifleman: 1.1
      soldier: 1.2
      spearman: 0.8
      structure: 0.7
      thief: 1.0
      trebuchet: 0.6
      villager: 1.0
      wagon: 0.75
      commander_caesar: 0.5
      commander_darkmercia: 0.4
      commander_elodie: 0.5
      commander_emeric: 0.5
      commander_greenfinger: 0.45
      commander_koji: 0.4
      commander_mercia: 0.45
      commander_mercival: 0.45
      commander_nuru: 0.45
      commander_ragna: 0.4
      commander_ryota: 0.5
      commander_sedge: 0.5
      commander_sigrid: 0.45
      commander_tenri: 0.45
      commander_twins: 0.5
      commander_valder: 0.5
      commander_vesper: 0.45
      commander_wulfar: 0.45
      balloon: 0.55
      dragon: 0.35
      harpoonship: 0.45
      harpy: 0.9
      travelboat: 0.6
      turtle: 0.55
      warship: 0.55
      witch: 0.7

modifyingUnitClasses:
  - id: commander_koji
    replace:
      cost: 750
      passiveMultiplier: 1.25
    remove:
      tags:
        - commander
    add:
      tags:
        - commander_koji

...
