---
weapons:
  - id: giantSlam
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
    tagDamage:
      archer: 1.5
      ballista: 1
      dog: 1.5
      giant: 0.45
      knight: 0.85
      mage: 1.1
      merman: 1.3
      rifleman: 1.4
      soldier: 1.3
      spearman: 1
      structure: 0.85
      thief: 1.3
      trebuchet: 1.05
      villager: 1.3
      wagon: 0.75
      commander_caesar: 0.4
      commander_darkmercia: 0.3
      commander_elodie: 0.4
      commander_emeric: 0.4
      commander_greenfinger: 0.35
      commander_koji: 0.3
      commander_mercia: 0.3
      commander_mercival: 0.35
      commander_nuru: 0.35
      commander_ragna: 0.3
      commander_ryota: 0.4
      commander_sedge: 0.4
      commander_sigrid: 0.35
      commander_tenri: 0.35
      commander_twins: 0.4
      commander_valder: 0.4
      commander_vesper: 0.35
      commander_wulfar: 0.35

---
