---
weapons:
  - id: bident
    rangeMin: 1
    rangeMax: 2
    canMoveAndAttack: true
    baseDamage:
      land: 1
      water: 1
    tagDamage:
      archer: 0.35
      ballista: 0.25
      dog: 0.45
      giant: 0.05
      harpoonship: 0.3
      knight: 0.15
      mage: 0.45
      merman: 0.25
      rifleman: 0.45
      soldier: 0.35
      spearman: 0.25
      structure: 0.15
      thief: 0.35
      travelboat: 0.1
      trebuchet: 0.2
      turtle: 0.1
      villager: 0.35
      wagon: 0.35
      warship: 0.05
      commander_caesar: 0.15
      commander_darkmercia: 0.05
      commander_elodie: 0.15
      commander_emeric: 0.15
      commander_greenfinger: 0.1
      commander_koji: 0.05
      commander_mercia: 0.05
      commander_mercival: 0.1
      commander_nuru: 0.1
      commander_ragna: 0.05
      commander_ryota: 0.15
      commander_sedge: 0.15
      commander_sigrid: 0.1
      commander_tenri: 0.1
      commander_twins: 0.15
      commander_valder: 0.15
      commander_vesper: 0.1
      commander_wulfar: 0.1

---
