---
weapons:
  - id: sword
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
    tagDamage:
      archer: 0.65
      ballista: 0.35
      dog: 0.45
      giant: 0.05
      knight: 0.15
      mage: 0.55
      merman: 0.55
      rifleman: 0.65
      soldier: 0.55
      spearman: 0.35
      structure: 0.35
      thief: 0.95
      trebuchet: 0.3
      villager: 0.55
      wagon: 0.35
      commander_caesar: 0.15
      commander_darkmercia: 0.05
      commander_elodie: 0.15
      commander_emeric: 0.15
      commander_greenfinger: 0.1
      commander_koji: 0.05
      commander_mercia: 0.05
      commander_mercival: 0.1
      commander_nuru: 0.1
      commander_ragna: 0.05
      commander_ryota: 0.15
      commander_sedge: 0.15
      commander_sigrid: 0.1
      commander_tenri: 0.1
      commander_twins: 0.15
      commander_valder: 0.15
      commander_vesper: 0.1
      commander_wulfar: 0.1

---
