---
weapons:
  - id: spear
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
    tagDamage:
      archer: 0.7
      ballista: 0.55
      dog: 0.8
      giant: 0.15
      knight: 0.7
      mage: 0.65
      merman: 0.75
      rifleman: 0.85
      soldier: 0.75
      spearman: 0.55
      structure: 0.5
      thief: 0.75
      trebuchet: 0.5
      villager: 0.75
      wagon: 0.45
      commander_caesar: 0.2
      commander_darkmercia: 0.1
      commander_elodie: 0.2
      commander_emeric: 0.2
      commander_greenfinger: 0.15
      commander_koji: 0.1
      commander_mercia: 0.1
      commander_mercival: 0.15
      commander_nuru: 0.15
      commander_ragna: 0.1
      commander_ryota: 0.2
      commander_sedge: 0.2
      commander_sigrid: 0.15
      commander_tenri: 0.15
      commander_twins: 0.2
      commander_valder: 0.2
      commander_vesper: 0.15
      commander_wulfar: 0.15

---
