---
weapons:
  - id: warshipCannon
    rangeMin: 2
    rangeMax: 4
    canMoveAndAttack: true
    baseDamage:
      land: 1
      water: 1
    tagDamage:
      archer: 1.2
      ballista: 0.85
      dog: 1.1
      giant: 0.55
      harpoonship: 0.8
      knight: 0.7
      mage: 0.8
      merman: 0.75
      rifleman: 1.1
      soldier: 1.0
      spearman: 0.75
      structure: 0.75
      thief: 1.0
      travelboat: 0.65
      trebuchet: 0.8
      turtle: 0.3
      villager: 1.0
      wagon: 0.6
      warship: 0.55
      commander_caesar: 0.3
      commander_darkmercia: 0.2
      commander_elodie: 0.3
      commander_emeric: 0.3
      commander_greenfinger: 0.25
      commander_koji: 0.2
      commander_mercia: 0.2
      commander_mercival: 0.25
      commander_nuru: 0.25
      commander_ragna: 0.2
      commander_ryota: 0.3
      commander_sedge: 0.3
      commander_sigrid: 0.25
      commander_tenri: 0.25
      commander_twins: 0.3
      commander_valder: 0.3
      commander_vesper: 0.25
      commander_wulfar: 0.25

---
